// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
<<<<<<< HEAD
            "name": "Ilya Veselov"
=======
            "name": "Ilya Veselov",
            "email": "notmydev@gmail.com"
>>>>>>> 5eb6183789bd260060346633ba43e2e76018b474
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
<<<<<<< HEAD
        "/calculate": {
=======
        "/v1/calculate": {
>>>>>>> 5eb6183789bd260060346633ba43e2e76018b474
            "post": {
                "description": "Calculate instructions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
<<<<<<< HEAD
=======
                "tags": [
                    "calculation"
                ],
>>>>>>> 5eb6183789bd260060346633ba43e2e76018b474
                "summary": "Calculate instructions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
<<<<<<< HEAD
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.Result"
                            }
=======
                            "$ref": "#/definitions/entity.Result"
>>>>>>> 5eb6183789bd260060346633ba43e2e76018b474
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
<<<<<<< HEAD
                            "$ref": "#/definitions/httpserver.ErrorResponse"
=======
                            "$ref": "#/definitions/errors.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPError"
>>>>>>> 5eb6183789bd260060346633ba43e2e76018b474
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.Result": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "integer"
                },
                "var": {
                    "type": "string"
                }
            }
        },
<<<<<<< HEAD
        "httpserver.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
=======
        "errors.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "status bad request"
>>>>>>> 5eb6183789bd260060346633ba43e2e76018b474
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Calculator API",
	Description:      "This is a simple calculator API that provides basic arithmetic operations.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
